### ISSUE TITLE
How can I save model parameters? I want to load the pre-trained model by myself in other experiments

### ISSUE THREAD

**Issue by Phoebe-ovo** [yandex-research/tabular-dl-num-embeddings#16]
I observed that: the checkpoint.pt only save:
report, study, trail_reports, timer, random_state.
I want to save the model parameters which can be loaded by anyone else.

**Comment by Yura52** [comment]
We don't save all model checkpoints during hyperparameter tuning, because that would consume significant amount of memory.

How to implement:
- rename `trial_reports` to `trial_results`
- [here](https://github.com/yandex-research/tabular-dl-num-embeddings/blob/c1d9eb63c0685b51d7e1bc081cdce6ffdb8886a8/bin/tune.py#L137), do `trial_results.append((report, model_state_dict))` where `model_state_dict` is extracted from `checkpoint.pt` located in the `dir_` directory [here](https://github.com/yandex-research/tabular-dl-num-embeddings/blob/c1d9eb63c0685b51d7e1bc081cdce6ffdb8886a8/bin/tune.py#L119C43-L119C47)
```
- change [the callback](https://github.com/yandex-research/tabular-dl-num-embeddings/blob/c1d9eb63c0685b51d7e1bc081cdce6ffdb8886a8/bin/tune.py#L141) accordingly

```

by adding `trial_models`
Saving all checkpoints during tuning

**Comment by Phoebe-ovo** [comment]
Thank you!
